### ISSUE TITLE
iOS Mail clipboard sharing duplicated text

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/capacitor-share-extension#1]
when I highlight a text selection in Mail in iOS 13 and then share it via the extension, the text is pasted in the message twice.

<img width="724" alt="Screen Shot 2020-12-24 at 3 13 10 PM" src="https://user-images.githubusercontent.com/23274587/103108212-8b87b780-45fa-11eb-98bc-cd5aaf5295de.png">

@Jdatechong I hope you are doing well! I don't know if you have time to look into this. If you do, do you know the reason of this issue?

**Comment by CodeTriager** [comment]
Does anyone of you know how the url scheme must be for ios? I just can't get it working..
