### ISSUE TITLE
Unable to Open Android app when using with Capacitor 4

### ISSUE THREAD

**Issue by brumscotto** [calvinckho/capacitor-share-extension#4]
Works well on iOS, but I'm having issues with Android. 

App appears in the share-to list and works as expected when outside the app (opens the app and processes Intent), but the app is now inaccessible in the app tray or on home page (it is visible from "Apps & Notifications" in Settings, but option to "Open" is not showing). 

Logs showing several "Invalid ID 0x00000000." Errors...

I have uninstalled/reinstalled, cleared storage & cache, rerun "npx cap sync android", invalidated the IDE cache, nothing has solved the issue.

**Comment by brumscotto** [comment]
<img width="1459" alt="Screen Shot 2022-11-01 at 10 19 54 AM" src="https://user-images.githubusercontent.com/43626530/199276464-601bda8f-1aa5-450e-873d-5363f9720e4a.png">

if additional error information is helpful...

**Comment by brumscotto** [comment]
<img width="2032" alt="Screen Shot 2022-11-01 at 11 46 48 AM" src="https://user-images.githubusercontent.com/43626530/199276606-6d1d1824-b8c2-443e-b479-db52257618ae.png">

if additional error information is helpful

**Comment by calvinckho** [comment]
I double checked my Capacitor 4 sample app and it works fine with no problem. 

Unfortunately, I wouldn't be able to help you further without taking a look at your Android project. I suspect that it has to do with your Android project setup. You may want to uninstall the plugin, revert the code in the MainActivity.java and AndroidManifest.xml, and make sure the Android app runs fine. Then, re-introduce the plugin and the code insertion to isolate the problem.
