### ISSUE TITLE
SendIntent doesn't fire when attaching file to current instance

### ISSUE THREAD

**Issue by CodeTriager** [calvinckho/capacitor-share-extension#7]
I'm using the Plugin to receive files in android. When I share files from the Google Files App the sendIntent functions fires and it works as expected. The Google Files App always opens a new instance of the app and closes the old one. I set `android:launchMode="singleTask"` because I only want to have one instance and attach the files to current because restarting the app is super annoying. But when I now share files from another App like Google Drive, Adobe Acrobat etc. the current instance of the app is opened again, but the sendIntent function doesn't fire. In my opinion the event should always fire when a shared file is received.

**Comment by calvinckho** [comment]
You need add event listener so the app is always listening to the firing of the event. 

Please see my sample implementation in https://github.com/calvinckho/capacitor-share-extension/issues/5#issuecomment-1341986101

**Comment by CodeTriager** [comment]
I added the code excalty like you did. But still the intent only fires when I share files from the google files app and therefor replaces the instance of the app. If the current instance is openend when I share files the plugin doesn't fire.

**Comment by calvinckho** [comment]
iOS or Android?

**Comment by CodeTriager** [comment]
Android only, IOS works fine.

**Comment by calvinckho** [comment]
Did you modify /android/app/src/main/java/.../MainActivity.java by following the instructions? You may want to insert console log commands in the various places to debug what went wrong.

**Comment by calvinckho** [comment]
I haven't heard from you for over a month. I will close it for now. You can reopen this issue if it continues to be an issue.
