### ISSUE TITLE
Cannot find type 'JSObject' in scope (capacitor@2)

### ISSUE THREAD

**Issue by NickHatBoecker** [calvinckho/capacitor-share-extension#8]
Hello,

I try to use this approach with Capacitor2 but in `CapacitorShareExtension/Plugin.swift` I get an error "*Cannot find type 'JSObject' in scope*" for the following line:

```swift
let payload: Array<JSObject> = store.shareItems.count > 0 ? Array(store.shareItems[0...]) : []
```

Target iOS version is 13.0.
Can you please help?

**Comment by calvinckho** [comment]
How did you install the plugin? Via npm or using github branch?

**Comment by NickHatBoecker** [comment]
Via npm. I had to add the `typealias JSObject = [String:Any]` at the top of `AppDelegate.swift`. Now it works :v:
